### PR TITLE
Add support for sub-state machines

### PR DESCRIPTION
**Pull request by galister**
Hello and thanks for this wonderful tool!

In this PR, I've added a new base class for `AacFlState` and `AacFlStateMachine` called `AacAnimatorNode<T>` which contains common code, such as placement of nodes.

Child nodes of an `AacFlStateMachine` are stored in `_childNodes` upon creation, so that node layout between state and state machines is consistent.

`AacTransitionEndpoint` is now used for sources & destinations of transition wrappers. This can contain either an `AnimatorState` or `AnimatorStateMachine`. It is expected that if the `AacTransitionEndpoint` is not null then one of its members will also not be null; this is checked using exceptions.

Syntax for StateMachines the same as for States:

```c#
var l = aac.CreateSupportingFxLayer("Face");
l.WithAvatarMaskNoTransforms();

var moodMachine = l.NewStateMachine("Default");
moodMachine.TransitionsFromEntry().When(moodParam.IsEqualTo(0));
moodMachine.Exits().When(moodParam.IsNotEqualTo(0));

var state = moodMachine.NewState("Default");
state.TransitionsFromEntry().When(...);
state.Exits().WithTransitionDurationSeconds(transitionTime).When(...);
```

Also changed `ResolveAvatarMask` and `WithAvatarMaskNoTransforms` functions (since they were void) to return the `AvatarMask` created so that the user can edit / re-use it further without much hassle.

Please let me know what you think.

### CODE REVIEW

**Comment by hai-vr** [comment]
Thank you, I won't be able to take a look at it today but I will.

See discussion on Discord, but here's a non-exhaustive task list of what I have to do:
- [ ] Discuss a real world use case for sub state machines and example code that consumes this new API to ensure that the exposed API feels right, the objective being to facilitate the creation of sub state machines (opinionated API)
- [ ] Verify that layer creation and removal does not leave non-destroyed internal assets behind lingering in the controller
- [ ] Evaluate the addition of possible `(AacFlLayer/AacFlStateMachine).Entry()` methods to be able to move Entry/Exit positions, and use them as targets for transitions

**Comment by galister** [comment]
here's the script I'm using right now. `FaceMood.GetMoods` reads the motion files and metadata from the folder structure.

```c#
var l = aac.CreateSupportingFxLayer("Face");
l.WithAvatarMaskNoTransforms();

var moodParam = l.IntParameter("_Activity");
var gestureLeft = l.IntParameter("GestureLeft");
var gestureRight = l.IntParameter("GestureRight");

var state = l.NewState("10_Bypass");
state.TransitionsFromEntry().When(moodParam.IsEqualTo(10));
state.Exits().When(moodParam.IsNotEqualTo(10));

foreach (var mood in FaceMood.GetMoods(_data, aac))
{
    var moodMachine = l.NewStateMachine($"{mood.Id}_{mood.Name}");
    moodMachine.TransitionsFromEntry().When(moodParam.IsEqualTo(mood.Id));
    moodMachine.Exits().When(moodParam.IsNotEqualTo(mood.Id));

    foreach (var category in mood.Categories)
    {
        var catMachine = moodMachine.NewStateMachine(category.Name);
        category.LeftGestureInts.Aggregate(
            catMachine.Exits().When(moodParam.IsNotEqualTo(mood.Id)).Or().WhenConditions(),
            (c, i) => c.And(gestureLeft.IsNotEqualTo(i)));

        foreach (var i in category.LeftGestureInts)
            catMachine.TransitionsFromEntry().When(gestureLeft.IsEqualTo(i));

        foreach (var g in category.RightGestures)
        {
            state = catMachine.NewState(g.HandGesture).WithAnimation(g.Motion)
                .Drives(l.BoolParameter("_Blink"), g.WantBlink)
                .Drives(l.IntParameter("_EarL"), g.EarL)
                .Drives(l.IntParameter("_EarR"), g.EarR);
            state.TransitionsFromEntry().When(gestureRight.IsEqualTo(g.Id));
            state.Exits().WithTransitionDurationSeconds(mood.TransitionTime).When(gestureRight.IsNotEqualTo(g.Id));
            state.Exits().WithTransitionDurationSeconds(mood.TransitionTime).When(moodParam.IsNotEqualTo(mood.Id));
            
            category.LeftGestureInts.Aggregate(
                state.Exits().WithTransitionDurationSeconds(mood.TransitionTime).WhenConditions(), 
                (c, i) => c.And(gestureLeft.IsNotEqualTo(i)));
        }
        
        // if no other exit was hit, just re-enter the current ssm
        catMachine.Restarts();
    }
    
    moodMachine.Restarts();
}
```

**Comment by galister** [comment]
top level state machine - each state/sub-state machine in here corresponds to an Activity value, from exp menu
image

2nd level state-machine - each SSM in here corresponds to one or more GestureLeft values
image

3rd level state-machine - each state in here corresponds to a single GestureRight value
image

**Comment by hai-vr** [comment]
The following commits are effectively part of V1, almost verbatim:

- add AacFlStateMachine.Restarts() for self-transitions galister* 19/03/2022 21:26
- format & refactor galister* 19/03/2022 12:08
- default location of new nodes more to the right galister* 19/03/2022 12:03
-add support for sub-state machines galister* 19/03/2022 12:03

The commit "avatarMask functions to return the generated mask" will not as these functions now return an AacFlLayer instead of void/AvatarMask

**Comment by hai-vr** [comment]
Closing, as the commits are effectively in the WIP V1 branch 👍 
Can't get GitHub to recognize this PR as being merged

**Pull request closed without merging**
